export const FETCH_ALL_QUESTIONS = "FETCH_ALL_QUESTIONS";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAILURE = "FETCH_FAILURE";

export const FETCH_NEXT_QUESTION = "FETCH_NEXT_QUESTION";